//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEABD
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluacionArticulo
    {
        public int id_revisorArticulo { get; set; }
        public int calificacion { get; set; }
        public string observaciones { get; set; }
        public System.DateTime fecha { get; set; }
        public int gradoExpertiz { get; set; }
        public string estado { get; set; }
    
        public virtual RevisorArticulo RevisorArticulo { get; set; }
    }
}
