//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEABD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int id_pago { get; set; }
        public Nullable<int> id_actividad { get; set; }
        public Nullable<int> id_asistente { get; set; }
        public Nullable<int> id_evento { get; set; }
        public Nullable<int> id_articulo { get; set; }
        public double cantidad { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Actividad Actividad { get; set; }
        public virtual Articulo Articulo { get; set; }
        public virtual Asistente Asistente { get; set; }
        public virtual Evento Evento { get; set; }
    }
}
