//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEABD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SigeaBD : DbContext
    {
        public SigeaBD()
            : base("name=SigeaBD")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actividad> Actividad { get; set; }
        public virtual DbSet<Adscripcion> Adscripcion { get; set; }
        public virtual DbSet<Articulo> Articulo { get; set; }
        public virtual DbSet<Asistente> Asistente { get; set; }
        public virtual DbSet<Autor> Autor { get; set; }
        public virtual DbSet<AutorArticulo> AutorArticulo { get; set; }
        public virtual DbSet<Comite> Comite { get; set; }
        public virtual DbSet<Cuenta> Cuenta { get; set; }
        public virtual DbSet<EvaluacionArticulo> EvaluacionArticulo { get; set; }
        public virtual DbSet<Evento> Evento { get; set; }
        public virtual DbSet<Gasto> Gasto { get; set; }
        public virtual DbSet<Magistral> Magistral { get; set; }
        public virtual DbSet<Organizador> Organizador { get; set; }
        public virtual DbSet<Pago> Pago { get; set; }
        public virtual DbSet<Presentacion> Presentacion { get; set; }
        public virtual DbSet<Revisor> Revisor { get; set; }
        public virtual DbSet<RevisorArticulo> RevisorArticulo { get; set; }
        public virtual DbSet<Tarea> Tarea { get; set; }
        public virtual DbSet<Track> Track { get; set; }
    }
}
